version: '3'
services:
  db:
    build:
      context: ./migration
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: false
  app:
    build:
      context: ./
    environment:
      User: root
      Pass: root
      Ip: golang_db
      PortDB: 3306
      PORT: 8080
    command: "go run ./service"
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: false
    depends_on:
      - db